```{r, child = "setup.Rmd", include = FALSE}
```

`r descr_models("decision_tree", "spark")`

## Tuning Parameters

```{r spark-param-info, echo = FALSE}
defaults <- 
  tibble::tibble(parsnip = c("tree_depth", "min_n"),
                 default = c("5L", "1L"))

param <-
 decision_tree() %>% 
  set_engine("spark") %>% 
  set_mode("regression") %>% 
  tunable() %>% 
  dplyr::select(-source, -component, -component_id, parsnip = name) %>% 
  dplyr::mutate(
    dials = purrr::map(call_info, get_dials),
    label = purrr::map_chr(dials, ~ .x$label),
    type = purrr::map_chr(dials, ~ .x$type)
  ) %>% 
  dplyr::full_join(defaults, by = "parsnip") %>% 
  mutate(
    item = 
      glue::glue("- `{parsnip}`: {label} (type: {type}, default: {default})\n\n")
  )
```

This model has `r nrow(param)` tuning parameters:

```{r spark-param-list, echo = FALSE, results = "asis"}
param$item
```

## Translation from parsnip to the original package (classification)

```{r spark-cls}
decision_tree(tree_depth = integer(1), min_n = integer(1)) %>% 
  set_engine("spark") %>% 
  set_mode("classification") %>% 
  translate()
```


## Translation from parsnip to the original package (regression)

```{r spark-reg}
decision_tree(tree_depth = integer(1), min_n = integer(1)) %>% 
  set_engine("spark") %>% 
  set_mode("regression") %>% 
  translate()
```

## Preprocessing requirements

```{r child = "template-split-factors.Rmd"}
```

## Other details

```{r child = "template-spark-notes.Rmd"}
```

## References

-   Kuhn, M, and K Johnson. 2013. *Applied Predictive Modeling*. Springer.

