```{r}
#| child: aaa.Rmd
#| include: false
```

`r descr_models("linear_reg", "h2o")`

## Tuning Parameters

```{r}
#| label: h2o-param-info
#| echo: false
defaults <- 
  tibble::tibble(parsnip = c("penalty", "mixture"),
                 default = c("see below", "see below"))

param <-
linear_reg() |> 
  set_engine("h2o") |> 
  make_parameter_list(defaults)
```

This model has `r nrow(param)` tuning parameters:

```{r}
#| label: h2o-param-list
#| echo: false
#| results: asis
param$item
```

```{r}
#| child: template-h2o-glm-penalty.Rmd
#| include: false
```

## Translation from parsnip to the original package

[agua::h2o_train_glm()] for `linear_reg()` is a wrapper around [h2o::h2o.glm()] with `family = "gaussian"`.


```{r}
#| label: h2o-csl
linear_reg(penalty = 1, mixture = 0.5) |> 
  set_engine("h2o") |> 
  translate()
```

## Preprocessing requirements

```{r}
#| child: template-makes-dummies.Rmd
```

```{r}
#| child: template-same-scale.Rmd
```

By default, [h2o::h2o.glm()] uses the argument `standardize = TRUE` to center and scale the data. 

## Initializing h2o 

```{r}
#| child: template-h2o-init.Rmd
```

## Saving fitted model objects

```{r}
#| child: template-bundle.Rmd
```
