# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# Add Config/Needs/website: tidyverse/tidytemplate to DESCRIPTION
on:
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [main, master]

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: r-lib/pkgdown
          needs: website

      - name: Install dev reticulate
        run: pak::pkg_install('rstudio/reticulate')
        shell: Rscript {0}

      - name: Install Miniconda
        # conda can fail at downgrading python, so we specify python version in advance
        env:
          RETICULATE_MINICONDA_PYTHON_VERSION: "3.7"
        run: reticulate::install_miniconda() # creates r-reticulate conda env by default
        shell: Rscript {0}

      - name: Install TensorFlow
        run: |
          tensorflow::install_tensorflow(version='2.7', conda_python_version = NULL)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build site
        if: github.event_name == 'pull_request'
        run: |
          Rscript -e 'pkgdown::build_site()'

      - name: Deploy package
        if: github.event_name == 'push'
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
